<?php

namespace Database\Factories;

use App\Models\Asset;
use App\Models\Organization;
use App\Models\User;
use Illuminate\Database\Eloquent\Factories\Factory;

class AssetFactory extends Factory
{
    protected $model = Asset::class;

    public function definition(): array
    {
        return [
            'organization_id' => Organization::factory(),
            'asset_code' => null, // Will be generated by model or controller
            'name' => $this->faker->words(3, true),
            'category' => $this->faker->randomElement(['Electronics', 'Furniture', 'Vehicles', 'Equipment', 'Tools']),
            'purchase_date' => $this->faker->dateTimeBetween('-2 years', 'now'),
            'purchase_price' => $this->faker->randomFloat(2, 100, 10000),
            'vendor' => $this->faker->optional()->company(),
            'warranty_expiry' => $this->faker->optional()->dateTimeBetween('now', '+2 years'),
            'status' => $this->faker->randomElement(['active', 'in_repair', 'retired']),
            'status_changed_at' => $this->faker->optional()->dateTimeBetween('-1 year', 'now'),
            'status_change_reason' => $this->faker->optional()->sentence(),
            'assigned_to_user_id' => null,
            'assigned_to_location' => $this->faker->optional()->randomElement(['Room 101', 'Room 202', 'Office A', 'Warehouse']),
            'description' => $this->faker->optional()->paragraph(),
            'serial_number' => $this->faker->optional()->bothify('SN-####-####'),
            'model_number' => $this->faker->optional()->bothify('MOD-####'),
            'notes' => $this->faker->optional()->sentence(),
        ];
    }

    public function forOrganization($organizationId)
    {
        return $this->state(function (array $attributes) use ($organizationId) {
            $org = Organization::find($organizationId);
            if (!$org) {
                // If organization doesn't exist, create a default code
                $prefix = 'ORG';
            } else {
                $prefix = strtoupper(substr($org->slug, 0, 3));
            }
            $year = date('Y');
            
            // Use a random number to avoid conflicts in tests
            // In production, the controller will generate proper sequential codes
            $randomNumber = str_pad($this->faker->unique()->numberBetween(1, 9999), 4, '0', STR_PAD_LEFT);
            
            return [
                'organization_id' => $organizationId,
                'asset_code' => "{$prefix}-{$year}-{$randomNumber}",
            ];
        });
    }

    public function active()
    {
        return $this->state(function (array $attributes) {
            return [
                'status' => 'active',
                'status_changed_at' => now(),
            ];
        });
    }

    public function inRepair()
    {
        return $this->state(function (array $attributes) {
            return [
                'status' => 'in_repair',
                'status_changed_at' => now(),
            ];
        });
    }

    public function retired()
    {
        return $this->state(function (array $attributes) {
            return [
                'status' => 'retired',
                'status_changed_at' => now(),
                'status_change_reason' => $this->faker->sentence(),
            ];
        });
    }
}
